### ISSUE TITLE
API Endpoints for Pipeline 

### ISSUE THREAD

**Issue by olssonandrew** [meadowdata/meadowrun-dallemini-demo#1]
I've been exploring this project and what meadowrun adds with the EC2 deployment of dall-e mega is brilliant. My goal is to extend the frontend react playground project to build an interface for each step of the pipeline (prompt, selecting candidate image for diffusion, and upscaling) in a user-friendly interface. Do you guys have any guidance on how those steps in the notebook could be converted to endpoints that I could reach them from a react frontend? I'm not too familiar with meadowrun or python deployments in EC2, so any guidance would be much appreciate!

**Comment by hrichardlee** [comment]
Take a look at the code in https://github.com/saharmor/dalle-playground/tree/main/backend That code is basically a Flask wrapper around the DALL-E Mini model. It sounds like you'll basically want to create new Flask wrappers around the diffusion model and the upscaling model.

**Comment by olssonandrew** [comment]
Oh excellent, that's really helpful. Thank you!
